"""Diretório de inicialização do módulo usecases"""
from .covid_cases_predict_interface import CovidCasesPredictInterface
from .register_country_interface import RegisterCountryInterface
from .get_countries_interface import GetCountriesInterface
from .get_covid_cases_interface import GetCovidCasesInterface
from .register_covid_cases_interface import RegisterCovidCasesInterface
from .covid_cases_colector_interface import CovidCasesColectorInterface
